-- Plugins
require "config.keymaps"
require("config.lazy")
require "config.options"
--require "user.plugins"
--require "user.colorscheme"
--require "user.cmp"
--require "user.lsp"
--require "user.telescope"
--require "user.treesitter"
--require "user.autopairs"
--require "user.comment"
--require "user.gitsigns"
--require "user.nvim-tree"
--require "user.bufferline"
--require "user.marks"
--require "user.lualine"
